require 'fission-package-builder/formatter/mail'
require 'fission-package-builder/formatter/slack'
require 'fission-package-builder/formatter/github_commit_comment'
require 'fission-package-builder/formatter/github_release'
require 'fission-package-builder/formatter/code_fetcher'
require 'fission-package-builder/formatter/repository_generator'
require 'fission-package-builder/formatter/packagecloud'
